### ISSUE TITLE
Cooky troubles

### ISSUE THREAD

**Issue by MyUncleSam** [chrRtg/eve-skylizer#4] opened 2018-05-04 07:08 UTC
It seems there is a cooky problem. If I log in on two different PCs one of them is getting on refresh the following error (if I delete all cookies from that page it is working again):

**Zend\ServiceManager\Exception\ServiceNotCreatedException**

**Message:**
`Service with name "User\Service\EveSSOManager" could not be created. Reason: Session validation failed`
**File:**
`/var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:771`

**StackTrace:**
```
#0 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(200): Zend\ServiceManager\ServiceManager->doCreate('User\\Service\\Ev...')
#1 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/module/User/src/Module.php(57): Zend\ServiceManager\ServiceManager->get('User\\Service\\Ev...')
#2 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): User\Module->onDispatch(Object(Zend\Mvc\MvcEvent))
#3 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#4 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#5 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#6 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#7 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#8 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#9 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/public/index.php(40): Zend\Mvc\Application->run()
#10 {main}
```

# Previous exception:
**Zend\Session\Exception\RuntimeException**

**Message:**
`Session validation failed`

**File:**
`/var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/vendor/zendframework/zend-session/src/SessionManager.php:162`

**StackTrace:**
```
#0 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/vendor/zendframework/zend-session/src/AbstractContainer.php(83): Zend\Session\SessionManager->start()
#1 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/module/User/src/Service/Factory/EveSSOManagerFactory.php(18): Zend\Session\AbstractContainer->__construct('eve_sso', Object(Zend\Session\SessionManager))
#2 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(764): User\Service\Factory\EveSSOManagerFactory->__invoke(Object(Zend\ServiceManager\ServiceManager), 'User\\Service\\Ev...', NULL)
#3 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(200): Zend\ServiceManager\ServiceManager->doCreate('User\\Service\\Ev...')
#4 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/module/User/src/Module.php(57): Zend\ServiceManager\ServiceManager->get('User\\Service\\Ev...')
#5 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): User\Module->onDispatch(Object(Zend\Mvc\MvcEvent))
#6 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#7 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#8 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#9 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#10 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#12 /var/www/virtual/domain.tld/scan/htdocs/eve-skylizer/public/index.php(40): Zend\Mvc\Application->run()
#13 {main}
```

**Comment by chrRtg** [comment] 2018-05-04 07:19
Does this happen only if you log in from two different machines with the very same user login?

This would be hard to solve because the session is bound to the user.

**Comment by MyUncleSam** [comment] 2018-05-05 22:16
I think this is the problem but I cannot reproduce it, it happens not all the time. All I can tell you is this message and that it is not possible to logout. Maybe you should insert a "session validation failed" check and if it failed redirect to main page or login page.

**Comment by chrRtg** [comment] 2018-05-10 12:54
I used skylizer with differnt browsers on the same machine as well from different devices at the same time with the same Eve char in all cases. Did a lot of clicks, even at the same time on different browsers/devices.
I'm sorry but I'm not able to reproduce your issue.

If you're able to reproduce the problem you may try to add one line to ./config/autoload/global.php.

into
```
 'session_config' => [
        'cookie_lifetime'     => 60*60*24*7, // Session cookie will expire in 7 days
        'gc_maxlifetime'      => 60*60*24*30, // How long to store session data on server (for 1 month).        
    ],
```
insert one line
```
 'session_config' => [
        'use_cookies'     => true,
        'cookie_lifetime'     => 60*60*24*7, // Session cookie will expire in 7 days
        'gc_maxlifetime'      => 60*60*24*30, // How long to store session data on server (for 1 month).        
    ],
```

**Comment by chrRtg** [comment] 2018-06-29 07:02
No feedback after a month, will close this issue now.

You may re-test. 

skylizer release 1.1 requires now PHP 7.1. After a composer update a lot of updates will arrive. And in the skylizer core I had updated a lot as well. From this perspective your problem might be solved. If not please let me know or feel free to re-open this issue.

**Closed as completed by chrRtg** 2018-06-29 07:02 UTC
